/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    2: typeof import('./src/components/icons/QA.vue')['default']
    3: typeof import('./src/components/icons/Fork copy 3.vue')['default']
    Account: typeof import('./src/components/icons/Account.vue')['default']
    AddFile: typeof import('./src/components/icons/AddFile.vue')['default']
    AddNodePopup: typeof import('./src/components/AddNodePopup.vue')['default']
    AddRound: typeof import('./src/components/icons/AddRound.vue')['default']
    BackGround: typeof import('./src/components/icons/BackGround.vue')['default']
    Cancle: typeof import('./src/components/icons/Cancle.vue')['default']
    Connect: typeof import('./src/components/icons/Connect.vue')['default']
    copy: typeof import('./src/components/icons/svg copy.vue')['default']
    Copy: typeof import('./src/components/icons/Copy.vue')['default']
    Delete: typeof import('./src/components/icons/Delete.vue')['default']
    DeleteRound: typeof import('./src/components/icons/DeleteRound.vue')['default']
    DownArrow: typeof import('./src/components/icons/DownArrow.vue')['default']
    Download: typeof import('./src/components/icons/Download.vue')['default']
    EchartsVisualization: typeof import('./src/components/EchartsVisualization.vue')['default']
    Edit: typeof import('./src/components/icons/Edit.vue')['default']
    Ellipsis: typeof import('./src/components/icons/Ellipsis.vue')['default']
    FileActionsMenu: typeof import('./src/components/FileActionsMenu.vue')['default']
    FileList: typeof import('./src/components/file-manager/FileList.vue')['default']
    FileTable: typeof import('./src/components/file-manager/FileTable.vue')['default']
    Folder: typeof import('./src/components/icons/Folder.vue')['default']
    FolderList: typeof import('./src/components/file-manager/FolderList.vue')['default']
    Fork: typeof import('./src/components/icons/Fork.vue')['default']
    Graph: typeof import('./src/components/icons/Graph.vue')['default']
    GraphBottom: typeof import('./src/components/GraphBottom.vue')['default']
    GraphFile: typeof import('./src/components/icons/GraphFile.vue')['default']
    HoverClickItem: typeof import('./src/components/HoverClickItem.vue')['default']
    KnowledgeGraph: typeof import('./src/components/KnowledgeGraph.vue')['default']
    MdFile: typeof import('./src/components/icons/MdFile.vue')['default']
    MixedFileList: typeof import('./src/components/file-manager/MixedFileList.vue')['default']
    NodeInfoPopup: typeof import('./src/components/NodeInfoPopup.vue')['default']
    OpenFolder: typeof import('./src/components/icons/OpenFolder.vue')['default']
    OperationToolbar: typeof import('./src/components/file-manager/OperationToolbar.vue')['default']
    QA: typeof import('./src/components/icons/QA.vue')['default']
    QA2: typeof import('./src/components/icons/QA2.vue')['default']
    Remove: typeof import('./src/components/icons/Remove.vue')['default']
    RightArrow: typeof import('./src/components/icons/RightArrow.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./src/components/icons/Search.vue')['default']
    Sidebar: typeof import('./src/components/Sidebar.vue')['default']
    Svg: typeof import('./src/components/icons/svg.vue')['default']
    Upload: typeof import('./src/components/icons/Upload.vue')['default']
  }
}
