/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    2: typeof import('./src/components/icons/QA.vue')['default']
    3: typeof import('./src/components/icons/Fork copy 3.vue')['default']
    Account: typeof import('./src/components/icons/Account.vue')['default']
    EchartsVisualization: typeof import('./src/components/EchartsVisualization.vue')['default']
    Edit: typeof import('./src/components/icons/Edit.vue')['default']
    Folder: typeof import('./src/components/icons/Folder.vue')['default']
    Fork: typeof import('./src/components/icons/Fork.vue')['default']
    Graph: typeof import('./src/components/icons/Graph.vue')['default']
    GraphFile: typeof import('./src/components/icons/GraphFile.vue')['default']
    HoverClickItem: typeof import('./src/components/HoverClickItem.vue')['default']
    KnowledgeGraph: typeof import('./src/components/KnowledgeGraph.vue')['default']
    MdFile: typeof import('./src/components/icons/MdFile.vue')['default']
    NodeInfoPopup: typeof import('./src/components/NodeInfoPopup.vue')['default']
    QA: typeof import('./src/components/icons/QA.vue')['default']
    RightArrow: typeof import('./src/components/icons/RightArrow.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./src/components/Sidebar.vue')['default']
    Svg: typeof import('./src/components/icons/svg.vue')['default']
  }
}
